// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Workspaces.Allowed_domain_auto_invite;
using Soenneker.Windmill.OpenApiClient.Workspaces.Create;
using Soenneker.Windmill.OpenApiClient.Workspaces.Delete;
using Soenneker.Windmill.OpenApiClient.Workspaces.Exists;
using Soenneker.Windmill.OpenApiClient.Workspaces.Exists_username;
using Soenneker.Windmill.OpenApiClient.Workspaces.List;
using Soenneker.Windmill.OpenApiClient.Workspaces.List_as_superadmin;
using Soenneker.Windmill.OpenApiClient.Workspaces.Unarchive;
using Soenneker.Windmill.OpenApiClient.Workspaces.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.Workspaces
{
    /// <summary>
    /// Builds and executes requests for operations under \workspaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The allowed_domain_auto_invite property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Allowed_domain_auto_invite.Allowed_domain_auto_inviteRequestBuilder Allowed_domain_auto_invite
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Allowed_domain_auto_invite.Allowed_domain_auto_inviteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exists property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Exists.ExistsRequestBuilder Exists
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Exists.ExistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exists_username property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Exists_username.Exists_usernameRequestBuilder Exists_username
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Exists_username.Exists_usernameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_as_superadmin property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.List_as_superadmin.List_as_superadminRequestBuilder List_as_superadmin
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.List_as_superadmin.List_as_superadminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unarchive property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Unarchive.UnarchiveRequestBuilder Unarchive
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Unarchive.UnarchiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Workspaces.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Windmill.OpenApiClient.Workspaces.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Workspaces.WorkspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Workspaces.WorkspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/workspaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
