// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Integrations.List
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum List_service_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "nextcloud")]
        #pragma warning disable CS1591
        Nextcloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "google")]
        #pragma warning disable CS1591
        Google,
        #pragma warning restore CS1591
        [EnumMember(Value = "github")]
        #pragma warning disable CS1591
        Github,
        #pragma warning restore CS1591
    }
}
