// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Acknowledge_all;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Item;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Mute;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\workspaces\critical_alerts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Critical_alertsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acknowledge_all property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Acknowledge_all.Acknowledge_allRequestBuilder Acknowledge_all
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Acknowledge_all.Acknowledge_allRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mute property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Mute.MuteRequestBuilder Mute
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Mute.MuteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.w.item.workspaces.critical_alerts.item collection</summary>
        /// <param name="position">The ID of the critical alert to acknowledge</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Item.Critical_alertsItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Item.Critical_alertsItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Item.Critical_alertsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Critical_alertsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/critical_alerts{?acknowledged*,page*,page_size*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Critical_alertsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/critical_alerts{?acknowledged*,page*,page_size*}", rawUrl)
        {
        }
        /// <summary>
        /// Get all critical alerts for this workspace
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.WorkspaceGetCriticalAlerts200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.WorkspaceGetCriticalAlerts200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder.Critical_alertsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.WorkspaceGetCriticalAlerts200> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder.Critical_alertsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Windmill.OpenApiClient.Models.WorkspaceGetCriticalAlerts200>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.WorkspaceGetCriticalAlerts200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get all critical alerts for this workspace
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder.Critical_alertsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder.Critical_alertsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get all critical alerts for this workspace
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Critical_alertsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("acknowledged")]
            public bool? Acknowledged { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
        }
    }
}
#pragma warning restore CS0618
