// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>
    /// A single step in a flow. Can be a script, subflow, loop, or branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateFlowRequestValueFailureModule : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache_ignore_s3_path property</summary>
        public bool? CacheIgnoreS3Path { get; set; }
        /// <summary>Cache duration in seconds for this step&apos;s results</summary>
        public double? CacheTtl { get; set; }
        /// <summary>If true, flow continues even if this step fails</summary>
        public bool? ContinueOnError { get; set; }
        /// <summary>Debounce configuration for this step (EE only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleDebouncing? Debouncing { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleDebouncing Debouncing { get; set; }
#endif
        /// <summary>If set, delete the step&apos;s args, result and logs after this many seconds following job completion</summary>
        public int? DeleteAfterSecs { get; set; }
        /// <summary>Unique identifier for this step. Used to reference results via &apos;results.step_id&apos;. Must be a valid identifier (alphanumeric, underscore, hyphen)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Mock configuration for testing without executing the actual step</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleMock? Mock { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleMock Mock { get; set; }
#endif
        /// <summary>Execution priority for this step (higher numbers run first)</summary>
        public double? Priority { get; set; }
        /// <summary>Retry configuration for failed module executions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleRetry? Retry { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleRetry Retry { get; set; }
#endif
        /// <summary>Conditionally skip this step based on previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSkipIf? SkipIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSkipIf SkipIf { get; set; }
#endif
        /// <summary>Maps input parameters for a step. Can be a static value or a JavaScript expression that references previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSleep? Sleep { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSleep Sleep { get; set; }
#endif
        /// <summary>Early termination condition for a module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterAllItersIf? StopAfterAllItersIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterAllItersIf StopAfterAllItersIf { get; set; }
#endif
        /// <summary>Early termination condition for a module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterIf? StopAfterIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterIf StopAfterIf { get; set; }
#endif
        /// <summary>Short description of what this step does</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>Configuration for approval/resume steps that wait for user input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSuspend? Suspend { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSuspend Suspend { get; set; }
#endif
        /// <summary>Maps input parameters for a step. Can be a static value or a JavaScript expression that references previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleTimeout? Timeout { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleTimeout Timeout { get; set; }
#endif
        /// <summary>The actual implementation of a flow step. Can be a script (inline or referenced), subflow, loop, branch, or special module type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleValue? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleValue Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModule"/> and sets the default values.
        /// </summary>
        public CreateFlowRequestValueFailureModule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache_ignore_s3_path", n => { CacheIgnoreS3Path = n.GetBoolValue(); } },
                { "cache_ttl", n => { CacheTtl = n.GetDoubleValue(); } },
                { "continue_on_error", n => { ContinueOnError = n.GetBoolValue(); } },
                { "debouncing", n => { Debouncing = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleDebouncing>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleDebouncing.CreateFromDiscriminatorValue); } },
                { "delete_after_secs", n => { DeleteAfterSecs = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mock", n => { Mock = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleMock>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleMock.CreateFromDiscriminatorValue); } },
                { "priority", n => { Priority = n.GetDoubleValue(); } },
                { "retry", n => { Retry = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleRetry>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleRetry.CreateFromDiscriminatorValue); } },
                { "skip_if", n => { SkipIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSkipIf>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSkipIf.CreateFromDiscriminatorValue); } },
                { "sleep", n => { Sleep = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSleep>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSleep.CreateFromDiscriminatorValue); } },
                { "stop_after_all_iters_if", n => { StopAfterAllItersIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterAllItersIf>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterAllItersIf.CreateFromDiscriminatorValue); } },
                { "stop_after_if", n => { StopAfterIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterIf>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterIf.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "suspend", n => { Suspend = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSuspend>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSuspend.CreateFromDiscriminatorValue); } },
                { "timeout", n => { Timeout = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleTimeout>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleTimeout.CreateFromDiscriminatorValue); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleValue>(global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cache_ignore_s3_path", CacheIgnoreS3Path);
            writer.WriteDoubleValue("cache_ttl", CacheTtl);
            writer.WriteBoolValue("continue_on_error", ContinueOnError);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleDebouncing>("debouncing", Debouncing);
            writer.WriteIntValue("delete_after_secs", DeleteAfterSecs);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleMock>("mock", Mock);
            writer.WriteDoubleValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleRetry>("retry", Retry);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSkipIf>("skip_if", SkipIf);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSleep>("sleep", Sleep);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterAllItersIf>("stop_after_all_iters_if", StopAfterAllItersIf);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleStopAfterIf>("stop_after_if", StopAfterIf);
            writer.WriteStringValue("summary", Summary);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleSuspend>("suspend", Suspend);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleTimeout>("timeout", Timeout);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateFlowRequestValueFailureModuleValue>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
