// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateScriptRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The assets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestAssetsItem>? Assets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestAssetsItem> Assets { get; set; }
#endif
        /// <summary>The auto_kind property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoKind { get; set; }
#nullable restore
#else
        public string AutoKind { get; set; }
#endif
        /// <summary>When true, the backend resolves the parent to the current deployed head for this path within the transaction (ignoring parent_hash), instead of failing with a &quot;lineage must be linear&quot; error when the supplied parent_hash is stale.</summary>
        public bool? AutoParent { get; set; }
        /// <summary>The cache_ignore_s3_path property</summary>
        public bool? CacheIgnoreS3Path { get; set; }
        /// <summary>The cache_ttl property</summary>
        public double? CacheTtl { get; set; }
        /// <summary>The codebase property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Codebase { get; set; }
#nullable restore
#else
        public string Codebase { get; set; }
#endif
        /// <summary>The concurrency_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConcurrencyKey { get; set; }
#nullable restore
#else
        public string ConcurrencyKey { get; set; }
#endif
        /// <summary>The concurrency_time_window_s property</summary>
        public int? ConcurrencyTimeWindowS { get; set; }
        /// <summary>The concurrent_limit property</summary>
        public int? ConcurrentLimit { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>The debounce_args_to_accumulate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DebounceArgsToAccumulate { get; set; }
#nullable restore
#else
        public List<string> DebounceArgsToAccumulate { get; set; }
#endif
        /// <summary>The debounce_delay_s property</summary>
        public int? DebounceDelayS { get; set; }
        /// <summary>The debounce_key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DebounceKey { get; set; }
#nullable restore
#else
        public string DebounceKey { get; set; }
#endif
        /// <summary>The dedicated_worker property</summary>
        public bool? DedicatedWorker { get; set; }
        /// <summary>If set, delete the job&apos;s args, result and logs after this many seconds following job completion</summary>
        public int? DeleteAfterSecs { get; set; }
        /// <summary>The deployment_message property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentMessage { get; set; }
#nullable restore
#else
        public string DeploymentMessage { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The envs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Envs { get; set; }
#nullable restore
#else
        public List<string> Envs { get; set; }
#endif
        /// <summary>The has_preprocessor property</summary>
        public bool? HasPreprocessor { get; set; }
        /// <summary>The is_template property</summary>
        public bool? IsTemplate { get; set; }
        /// <summary>The kind property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestKind? Kind { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>The language property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestLanguage? Language { get; set; }
        /// <summary>The lock property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lock { get; set; }
#nullable restore
#else
        public string Lock { get; set; }
#endif
        /// <summary>The max_total_debounces_amount property</summary>
        public int? MaxTotalDebouncesAmount { get; set; }
        /// <summary>The max_total_debouncing_time property</summary>
        public int? MaxTotalDebouncingTime { get; set; }
        /// <summary>Additional script modules keyed by relative file path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestModules? Modules { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestModules Modules { get; set; }
#endif
        /// <summary>Authorization identity to run as: u/{username}, g/{group}, or a bare email when the username is itself email-shaped. Supply this or on_behalf_of_email; when only the address is given it is resolved to the account it names, and an address naming nobody is rejected. A pair that disagrees is rejected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnBehalfOf { get; set; }
#nullable restore
#else
        public string OnBehalfOf { get; set; }
#endif
        /// <summary>The on_behalf_of_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnBehalfOfEmail { get; set; }
#nullable restore
#else
        public string OnBehalfOfEmail { get; set; }
#endif
        /// <summary>The hash of the version this one supersedes: deploying with it archives that version and chains the new one onto its history, and a `path` differing from the superseded version&apos;s moves the script there.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentHash { get; set; }
#nullable restore
#else
        public string ParentHash { get; set; }
#endif
        /// <summary>The path property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>When true and the caller is a member of the &apos;wm_deployers&apos; group, preserves the original on_behalf_of_email / on_behalf_of pair instead of overwriting it with the caller&apos;s own identity.</summary>
        public bool? PreserveOnBehalfOf { get; set; }
        /// <summary>The priority property</summary>
        public int? Priority { get; set; }
        /// <summary>The restart_unless_cancelled property</summary>
        public bool? RestartUnlessCancelled { get; set; }
        /// <summary>The schema property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestSchema? Schema { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestSchema Schema { get; set; }
#endif
        /// <summary>When true (set by the CLI / git sync), deploying this script does not delete an existing user draft at the same path.</summary>
        public bool? SkipDraftDeletion { get; set; }
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>The tag property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tag { get; set; }
#nullable restore
#else
        public string Tag { get; set; }
#endif
        /// <summary>The timeout property</summary>
        public int? Timeout { get; set; }
        /// <summary>The visible_to_runner_only property</summary>
        public bool? VisibleToRunnerOnly { get; set; }
        /// <summary>The ws_error_handler_muted property</summary>
        public bool? WsErrorHandlerMuted { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequest"/> and sets the default values.
        /// </summary>
        public CreateScriptRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assets", n => { Assets = n.GetCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestAssetsItem>(global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestAssetsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "auto_kind", n => { AutoKind = n.GetStringValue(); } },
                { "auto_parent", n => { AutoParent = n.GetBoolValue(); } },
                { "cache_ignore_s3_path", n => { CacheIgnoreS3Path = n.GetBoolValue(); } },
                { "cache_ttl", n => { CacheTtl = n.GetDoubleValue(); } },
                { "codebase", n => { Codebase = n.GetStringValue(); } },
                { "concurrency_key", n => { ConcurrencyKey = n.GetStringValue(); } },
                { "concurrency_time_window_s", n => { ConcurrencyTimeWindowS = n.GetIntValue(); } },
                { "concurrent_limit", n => { ConcurrentLimit = n.GetIntValue(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "debounce_args_to_accumulate", n => { DebounceArgsToAccumulate = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "debounce_delay_s", n => { DebounceDelayS = n.GetIntValue(); } },
                { "debounce_key", n => { DebounceKey = n.GetStringValue(); } },
                { "dedicated_worker", n => { DedicatedWorker = n.GetBoolValue(); } },
                { "delete_after_secs", n => { DeleteAfterSecs = n.GetIntValue(); } },
                { "deployment_message", n => { DeploymentMessage = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "envs", n => { Envs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "has_preprocessor", n => { HasPreprocessor = n.GetBoolValue(); } },
                { "is_template", n => { IsTemplate = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestKind>(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "language", n => { Language = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestLanguage>(); } },
                { "lock", n => { Lock = n.GetStringValue(); } },
                { "max_total_debounces_amount", n => { MaxTotalDebouncesAmount = n.GetIntValue(); } },
                { "max_total_debouncing_time", n => { MaxTotalDebouncingTime = n.GetIntValue(); } },
                { "modules", n => { Modules = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestModules>(global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestModules.CreateFromDiscriminatorValue); } },
                { "on_behalf_of", n => { OnBehalfOf = n.GetStringValue(); } },
                { "on_behalf_of_email", n => { OnBehalfOfEmail = n.GetStringValue(); } },
                { "parent_hash", n => { ParentHash = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "preserve_on_behalf_of", n => { PreserveOnBehalfOf = n.GetBoolValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "restart_unless_cancelled", n => { RestartUnlessCancelled = n.GetBoolValue(); } },
                { "schema", n => { Schema = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestSchema>(global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestSchema.CreateFromDiscriminatorValue); } },
                { "skip_draft_deletion", n => { SkipDraftDeletion = n.GetBoolValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "tag", n => { Tag = n.GetStringValue(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "visible_to_runner_only", n => { VisibleToRunnerOnly = n.GetBoolValue(); } },
                { "ws_error_handler_muted", n => { WsErrorHandlerMuted = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestAssetsItem>("assets", Assets);
            writer.WriteStringValue("auto_kind", AutoKind);
            writer.WriteBoolValue("auto_parent", AutoParent);
            writer.WriteBoolValue("cache_ignore_s3_path", CacheIgnoreS3Path);
            writer.WriteDoubleValue("cache_ttl", CacheTtl);
            writer.WriteStringValue("codebase", Codebase);
            writer.WriteStringValue("concurrency_key", ConcurrencyKey);
            writer.WriteIntValue("concurrency_time_window_s", ConcurrencyTimeWindowS);
            writer.WriteIntValue("concurrent_limit", ConcurrentLimit);
            writer.WriteStringValue("content", Content);
            writer.WriteCollectionOfPrimitiveValues<string>("debounce_args_to_accumulate", DebounceArgsToAccumulate);
            writer.WriteIntValue("debounce_delay_s", DebounceDelayS);
            writer.WriteStringValue("debounce_key", DebounceKey);
            writer.WriteBoolValue("dedicated_worker", DedicatedWorker);
            writer.WriteIntValue("delete_after_secs", DeleteAfterSecs);
            writer.WriteStringValue("deployment_message", DeploymentMessage);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("envs", Envs);
            writer.WriteBoolValue("has_preprocessor", HasPreprocessor);
            writer.WriteBoolValue("is_template", IsTemplate);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestKind>("kind", Kind);
            writer.WriteCollectionOfPrimitiveValues<string>("labels", Labels);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestLanguage>("language", Language);
            writer.WriteStringValue("lock", Lock);
            writer.WriteIntValue("max_total_debounces_amount", MaxTotalDebouncesAmount);
            writer.WriteIntValue("max_total_debouncing_time", MaxTotalDebouncingTime);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestModules>("modules", Modules);
            writer.WriteStringValue("on_behalf_of", OnBehalfOf);
            writer.WriteStringValue("on_behalf_of_email", OnBehalfOfEmail);
            writer.WriteStringValue("parent_hash", ParentHash);
            writer.WriteStringValue("path", Path);
            writer.WriteBoolValue("preserve_on_behalf_of", PreserveOnBehalfOf);
            writer.WriteIntValue("priority", Priority);
            writer.WriteBoolValue("restart_unless_cancelled", RestartUnlessCancelled);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.CreateScriptRequestSchema>("schema", Schema);
            writer.WriteBoolValue("skip_draft_deletion", SkipDraftDeletion);
            writer.WriteStringValue("summary", Summary);
            writer.WriteStringValue("tag", Tag);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteBoolValue("visible_to_runner_only", VisibleToRunnerOnly);
            writer.WriteBoolValue("ws_error_handler_muted", WsErrorHandlerMuted);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
