// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>
    /// Legacy flat format for editing success handler (deprecated, use new format)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EditSuccessHandlerMember2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Path to the success handler script or flow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SuccessHandler { get; set; }
#nullable restore
#else
        public string SuccessHandler { get; set; }
#endif
        /// <summary>The arguments to pass to the script or flow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2_success_handler_extra_args? SuccessHandlerExtraArgs { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2_success_handler_extra_args SuccessHandlerExtraArgs { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2"/> and sets the default values.
        /// </summary>
        public EditSuccessHandlerMember2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "success_handler", n => { SuccessHandler = n.GetStringValue(); } },
                { "success_handler_extra_args", n => { SuccessHandlerExtraArgs = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2_success_handler_extra_args>(global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2_success_handler_extra_args.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("success_handler", SuccessHandler);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.EditSuccessHandlerMember2_success_handler_extra_args>("success_handler_extra_args", SuccessHandlerExtraArgs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
