// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExperimentResults200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>One run of a dataset: written once when the dataset is run, and only ever read afterwards. The case set it executed is returned by the results endpoint, not here: a listing would otherwise send the whole dataset back once per experiment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseBaseline? Baseline { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseBaseline Baseline { get; set; }
#endif
        /// <summary>One run of a dataset: written once when the dataset is run, and only ever read afterwards. The case set it executed is returned by the results endpoint, not here: a listing would otherwise send the whole dataset back once per experiment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseExperiment? Experiment { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseExperiment Experiment { get; set; }
#endif
        /// <summary>The means property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseMeansItem>? Means { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseMeansItem> Means { get; set; }
#endif
        /// <summary>Cells scoring lower than the baseline, across every column.</summary>
        public int? Regressed { get; set; }
        /// <summary>The rows property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseRowsItem>? Rows { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseRowsItem> Rows { get; set; }
#endif
        /// <summary>The columns, which belong to the dataset rather than the experiment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseScorersItem>? Scorers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseScorersItem> Scorers { get; set; }
#endif
        /// <summary>The version the subject is on now. A row that ran against an earlier one describes an agent that no longer exists.</summary>
        public long? SubjectCurrentVersion { get; set; }
        /// <summary>What the agent hashes to as deployed. A run of unsaved edits carrying this hash ran exactly what is deployed now — the edits were saved — so it is a run of that version rather than of edits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SubjectDeployedHash { get; set; }
#nullable restore
#else
        public string SubjectDeployedHash { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200Response"/> and sets the default values.
        /// </summary>
        public ExperimentResults200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseline", n => { Baseline = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseBaseline>(global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseBaseline.CreateFromDiscriminatorValue); } },
                { "experiment", n => { Experiment = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseExperiment>(global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseExperiment.CreateFromDiscriminatorValue); } },
                { "means", n => { Means = n.GetCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseMeansItem>(global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseMeansItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "regressed", n => { Regressed = n.GetIntValue(); } },
                { "rows", n => { Rows = n.GetCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseRowsItem>(global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseRowsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "scorers", n => { Scorers = n.GetCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseScorersItem>(global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseScorersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject_current_version", n => { SubjectCurrentVersion = n.GetLongValue(); } },
                { "subject_deployed_hash", n => { SubjectDeployedHash = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseBaseline>("baseline", Baseline);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseExperiment>("experiment", Experiment);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseMeansItem>("means", Means);
            writer.WriteIntValue("regressed", Regressed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseRowsItem>("rows", Rows);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ExperimentResults200ResponseScorersItem>("scorers", Scorers);
            writer.WriteLongValue("subject_current_version", SubjectCurrentVersion);
            writer.WriteStringValue("subject_deployed_hash", SubjectDeployedHash);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
