// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>
    /// A single step in a flow. Can be a script, subflow, loop, or branch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetFlowByPathWithDraft200_draft_value_modules : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache_ignore_s3_path property</summary>
        public bool? CacheIgnoreS3Path { get; set; }
        /// <summary>Cache duration in seconds for this step&apos;s results</summary>
        public double? CacheTtl { get; set; }
        /// <summary>If true, flow continues even if this step fails</summary>
        public bool? ContinueOnError { get; set; }
        /// <summary>Debounce configuration for this step (EE only)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_debouncing? Debouncing { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_debouncing Debouncing { get; set; }
#endif
        /// <summary>If set, delete the step&apos;s args, result and logs after this many seconds following job completion</summary>
        public int? DeleteAfterSecs { get; set; }
        /// <summary>Unique identifier for this step. Used to reference results via &apos;results.step_id&apos;. Must be a valid identifier (alphanumeric, underscore, hyphen)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Mock configuration for testing without executing the actual step</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_mock? Mock { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_mock Mock { get; set; }
#endif
        /// <summary>Execution priority for this step (higher numbers run first)</summary>
        public double? Priority { get; set; }
        /// <summary>Retry configuration for failed module executions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_retry? Retry { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_retry Retry { get; set; }
#endif
        /// <summary>Conditionally skip this step based on previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_skip_if? SkipIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_skip_if SkipIf { get; set; }
#endif
        /// <summary>Maps input parameters for a step. Can be a static value or a JavaScript expression that references previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep? Sleep { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep Sleep { get; set; }
#endif
        /// <summary>Early termination condition for a module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_all_iters_if? StopAfterAllItersIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_all_iters_if StopAfterAllItersIf { get; set; }
#endif
        /// <summary>Early termination condition for a module</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_if? StopAfterIf { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_if StopAfterIf { get; set; }
#endif
        /// <summary>Short description of what this step does</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>Configuration for approval/resume steps that wait for user input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_suspend? Suspend { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_suspend Suspend { get; set; }
#endif
        /// <summary>Maps input parameters for a step. Can be a static value or a JavaScript expression that references previous results or flow inputs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout? Timeout { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout Timeout { get; set; }
#endif
        /// <summary>The actual implementation of a flow step. Can be a script (inline or referenced), subflow, loop, branch, or special module type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules"/> and sets the default values.
        /// </summary>
        public GetFlowByPathWithDraft200_draft_value_modules()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache_ignore_s3_path", n => { CacheIgnoreS3Path = n.GetBoolValue(); } },
                { "cache_ttl", n => { CacheTtl = n.GetDoubleValue(); } },
                { "continue_on_error", n => { ContinueOnError = n.GetBoolValue(); } },
                { "debouncing", n => { Debouncing = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_debouncing>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_debouncing.CreateFromDiscriminatorValue); } },
                { "delete_after_secs", n => { DeleteAfterSecs = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mock", n => { Mock = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_mock>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_mock.CreateFromDiscriminatorValue); } },
                { "priority", n => { Priority = n.GetDoubleValue(); } },
                { "retry", n => { Retry = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_retry>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_retry.CreateFromDiscriminatorValue); } },
                { "skip_if", n => { SkipIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_skip_if>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_skip_if.CreateFromDiscriminatorValue); } },
                { "sleep", n => { Sleep = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep.CreateFromDiscriminatorValue); } },
                { "stop_after_all_iters_if", n => { StopAfterAllItersIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_all_iters_if>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_all_iters_if.CreateFromDiscriminatorValue); } },
                { "stop_after_if", n => { StopAfterIf = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_if>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_if.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "suspend", n => { Suspend = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_suspend>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_suspend.CreateFromDiscriminatorValue); } },
                { "timeout", n => { Timeout = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout.CreateFromDiscriminatorValue); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value>(global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cache_ignore_s3_path", CacheIgnoreS3Path);
            writer.WriteDoubleValue("cache_ttl", CacheTtl);
            writer.WriteBoolValue("continue_on_error", ContinueOnError);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_debouncing>("debouncing", Debouncing);
            writer.WriteIntValue("delete_after_secs", DeleteAfterSecs);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_mock>("mock", Mock);
            writer.WriteDoubleValue("priority", Priority);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_retry>("retry", Retry);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_skip_if>("skip_if", SkipIf);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep>("sleep", Sleep);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_all_iters_if>("stop_after_all_iters_if", StopAfterAllItersIf);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_stop_after_if>("stop_after_if", StopAfterIf);
            writer.WriteStringValue("summary", Summary);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_suspend>("suspend", Suspend);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout>("timeout", Timeout);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetFlowByPathWithDraft200_draft_value_modules_sleep : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1? GetFlowByPathWithDraft200DraftValueModulesSleepMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1 GetFlowByPathWithDraft200DraftValueModulesSleepMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2? GetFlowByPathWithDraft200DraftValueModulesSleepMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2 GetFlowByPathWithDraft200DraftValueModulesSleepMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3? GetFlowByPathWithDraft200DraftValueModulesSleepMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3 GetFlowByPathWithDraft200DraftValueModulesSleepMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_sleep();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesSleepMember1 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesSleepMember2 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesSleepMember3 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GetFlowByPathWithDraft200DraftValueModulesSleepMember1 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesSleepMember1.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesSleepMember2 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesSleepMember2.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesSleepMember3 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesSleepMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GetFlowByPathWithDraft200DraftValueModulesSleepMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember1>(null, GetFlowByPathWithDraft200DraftValueModulesSleepMember1);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesSleepMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember2>(null, GetFlowByPathWithDraft200DraftValueModulesSleepMember2);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesSleepMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_sleepMember3>(null, GetFlowByPathWithDraft200DraftValueModulesSleepMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetFlowByPathWithDraft200_draft_value_modules_timeout : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1? GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1 GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2? GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2 GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3? GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3 GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_timeout();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember1>(null, GetFlowByPathWithDraft200DraftValueModulesTimeoutMember1);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember2>(null, GetFlowByPathWithDraft200DraftValueModulesTimeoutMember2);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_timeoutMember3>(null, GetFlowByPathWithDraft200DraftValueModulesTimeoutMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class GetFlowByPathWithDraft200_draft_value_modules_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1? GetFlowByPathWithDraft200DraftValueModulesValueMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1 GetFlowByPathWithDraft200DraftValueModulesValueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2? GetFlowByPathWithDraft200DraftValueModulesValueMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2 GetFlowByPathWithDraft200DraftValueModulesValueMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3? GetFlowByPathWithDraft200DraftValueModulesValueMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3 GetFlowByPathWithDraft200DraftValueModulesValueMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4? GetFlowByPathWithDraft200DraftValueModulesValueMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4 GetFlowByPathWithDraft200DraftValueModulesValueMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5? GetFlowByPathWithDraft200DraftValueModulesValueMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5 GetFlowByPathWithDraft200DraftValueModulesValueMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6? GetFlowByPathWithDraft200DraftValueModulesValueMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6 GetFlowByPathWithDraft200DraftValueModulesValueMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7? GetFlowByPathWithDraft200DraftValueModulesValueMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7 GetFlowByPathWithDraft200DraftValueModulesValueMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8? GetFlowByPathWithDraft200DraftValueModulesValueMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8 GetFlowByPathWithDraft200DraftValueModulesValueMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9? GetFlowByPathWithDraft200DraftValueModulesValueMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9 GetFlowByPathWithDraft200DraftValueModulesValueMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules.GetFlowByPathWithDraft200_draft_value_modules_value();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember1 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember2 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember3 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember4 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember5 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember6 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember7 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember8 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.GetFlowByPathWithDraft200DraftValueModulesValueMember9 = new global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(GetFlowByPathWithDraft200DraftValueModulesValueMember1 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember1.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember2 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember2.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember3 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember3.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember4 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember4.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember5 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember5.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember6 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember6.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember7 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember7.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember8 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember8.GetFieldDeserializers();
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember9 != null)
                {
                    return GetFlowByPathWithDraft200DraftValueModulesValueMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(GetFlowByPathWithDraft200DraftValueModulesValueMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember1>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember1);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember2>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember2);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember3>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember3);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember4>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember4);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember5>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember5);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember6>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember6);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember7>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember7);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember8>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember8);
                }
                else if(GetFlowByPathWithDraft200DraftValueModulesValueMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetFlowByPathWithDraft200_draft_value_modules_valueMember9>(null, GetFlowByPathWithDraft200DraftValueModulesValueMember9);
                }
            }
        }
    }
}
#pragma warning restore CS0618
