// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetFolderUsage_200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apps property</summary>
        public double? Apps { get; set; }
        /// <summary>The flows property</summary>
        public double? Flows { get; set; }
        /// <summary>The resources property</summary>
        public double? Resources { get; set; }
        /// <summary>The schedules property</summary>
        public double? Schedules { get; set; }
        /// <summary>The scripts property</summary>
        public double? Scripts { get; set; }
        /// <summary>The variables property</summary>
        public double? Variables { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFolderUsage_200"/> and sets the default values.
        /// </summary>
        public GetFolderUsage_200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetFolderUsage_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.GetFolderUsage_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.GetFolderUsage_200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apps", n => { Apps = n.GetDoubleValue(); } },
                { "flows", n => { Flows = n.GetDoubleValue(); } },
                { "resources", n => { Resources = n.GetDoubleValue(); } },
                { "schedules", n => { Schedules = n.GetDoubleValue(); } },
                { "scripts", n => { Scripts = n.GetDoubleValue(); } },
                { "variables", n => { Variables = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("apps", Apps);
            writer.WriteDoubleValue("flows", Flows);
            writer.WriteDoubleValue("resources", Resources);
            writer.WriteDoubleValue("schedules", Schedules);
            writer.WriteDoubleValue("scripts", Scripts);
            writer.WriteDoubleValue("variables", Variables);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
