// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFlowByPathWithDraft_200_value_failure_module_valueMember6_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "branchone")]
        #pragma warning disable CS1591
        Branchone,
        #pragma warning restore CS1591
    }
}
