// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetHttpTrigger200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How requests are authenticated - &apos;none&apos; (public), &apos;windmill&apos; (Windmill token), &apos;api_key&apos;, &apos;basic_http&apos;, &apos;custom_script&apos;, &apos;signature&apos;</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_authentication_method? AuthenticationMethod { get; set; }
        /// <summary>Path to the resource containing authentication configuration (for api_key, basic_http, custom_script, signature methods)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuthenticationResourcePath { get; set; }
#nullable restore
#else
        public string AuthenticationResourcePath { get; set; }
#endif
        /// <summary>Detailed description of what this trigger does</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The arguments to pass to the script or flow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_error_handler_args? ErrorHandlerArgs { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_error_handler_args ErrorHandlerArgs { get; set; }
#endif
        /// <summary>Path to a script or flow to run when the triggered job fails</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorHandlerPath { get; set; }
#nullable restore
#else
        public string ErrorHandlerPath { get; set; }
#endif
        /// <summary>HTTP method (get, post, put, delete, patch) that triggers this endpoint</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_http_method? HttpMethod { get; set; }
        /// <summary>If true, serves static files from S3/storage instead of running a script</summary>
        public bool? IsStaticWebsite { get; set; }
        /// <summary>If true, passes the request body as a raw string instead of parsing as JSON</summary>
        public bool? RawString { get; set; }
        /// <summary>How the request is handled - &apos;sync&apos; waits for result, &apos;async&apos; returns job ID immediately, &apos;sync_sse&apos; streams results via Server-Sent Events</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_request_type? RequestType { get; set; }
        /// <summary>Retry configuration for failed module executions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_retry? Retry { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_retry Retry { get; set; }
#endif
        /// <summary>The URL route path that will trigger this endpoint (e.g., &apos;api/myendpoint&apos;). Must NOT start with a /.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RoutePath { get; set; }
#nullable restore
#else
        public string RoutePath { get; set; }
#endif
        /// <summary>Configuration for serving static assets (s3 bucket, storage path, filename)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_static_asset_config? StaticAssetConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_static_asset_config StaticAssetConfig { get; set; }
#endif
        /// <summary>Short summary describing the purpose of this trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>If true, the route includes the workspace ID in the path</summary>
        public bool? WorkspacedRoute { get; set; }
        /// <summary>If true, wraps the request body in a &apos;body&apos; parameter</summary>
        public bool? WrapBody { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200"/> and sets the default values.
        /// </summary>
        public GetHttpTrigger200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "authentication_method", n => { AuthenticationMethod = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_authentication_method>(); } },
                { "authentication_resource_path", n => { AuthenticationResourcePath = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "error_handler_args", n => { ErrorHandlerArgs = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_error_handler_args>(global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_error_handler_args.CreateFromDiscriminatorValue); } },
                { "error_handler_path", n => { ErrorHandlerPath = n.GetStringValue(); } },
                { "http_method", n => { HttpMethod = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_http_method>(); } },
                { "is_static_website", n => { IsStaticWebsite = n.GetBoolValue(); } },
                { "raw_string", n => { RawString = n.GetBoolValue(); } },
                { "request_type", n => { RequestType = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_request_type>(); } },
                { "retry", n => { Retry = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_retry>(global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_retry.CreateFromDiscriminatorValue); } },
                { "route_path", n => { RoutePath = n.GetStringValue(); } },
                { "static_asset_config", n => { StaticAssetConfig = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_static_asset_config>(global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_static_asset_config.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "workspaced_route", n => { WorkspacedRoute = n.GetBoolValue(); } },
                { "wrap_body", n => { WrapBody = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_authentication_method>("authentication_method", AuthenticationMethod);
            writer.WriteStringValue("authentication_resource_path", AuthenticationResourcePath);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_error_handler_args>("error_handler_args", ErrorHandlerArgs);
            writer.WriteStringValue("error_handler_path", ErrorHandlerPath);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_http_method>("http_method", HttpMethod);
            writer.WriteBoolValue("is_static_website", IsStaticWebsite);
            writer.WriteBoolValue("raw_string", RawString);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_request_type>("request_type", RequestType);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_retry>("retry", Retry);
            writer.WriteStringValue("route_path", RoutePath);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHttpTrigger200_static_asset_config>("static_asset_config", StaticAssetConfig);
            writer.WriteStringValue("summary", Summary);
            writer.WriteBoolValue("workspaced_route", WorkspacedRoute);
            writer.WriteBoolValue("wrap_body", WrapBody);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
