// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8"/>, <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetHubFlowById200ResponseFlowValueModulesItemValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9? GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9 { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9 GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValue();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8.GetFieldDeserializers();
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9 != null)
            {
                return GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf1);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf2);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf3);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf4);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf5);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf6);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf7);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf8);
            }
            else if(GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9>(null, GetHubFlowById200ResponseFlowValueModulesItemValueOneOf9);
            }
        }
    }
}
#pragma warning restore CS0618
