// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>Type of asset</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetJob200ResponseOneOf1RawFlowPreprocessorModuleValueOneOf1AssetsItemKind
    {
        [EnumMember(Value = "s3object")]
        #pragma warning disable CS1591
        S3Object,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource")]
        #pragma warning disable CS1591
        Resource,
        #pragma warning restore CS1591
        [EnumMember(Value = "ducklake")]
        #pragma warning disable CS1591
        Ducklake,
        #pragma warning restore CS1591
        [EnumMember(Value = "datatable")]
        #pragma warning disable CS1591
        Datatable,
        #pragma warning restore CS1591
        [EnumMember(Value = "volume")]
        #pragma warning disable CS1591
        Volume,
        #pragma warning restore CS1591
        [EnumMember(Value = "dbt")]
        #pragma warning disable CS1591
        Dbt,
        #pragma warning restore CS1591
    }
}
