// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>job trigger kind (schedule, http, websocket...)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetJob200ResponseOneOf2TriggerKind
    {
        [EnumMember(Value = "webhook")]
        #pragma warning disable CS1591
        Webhook,
        #pragma warning restore CS1591
        [EnumMember(Value = "default_email")]
        #pragma warning disable CS1591
        DefaultEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "schedule")]
        #pragma warning disable CS1591
        Schedule,
        #pragma warning restore CS1591
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "websocket")]
        #pragma warning disable CS1591
        Websocket,
        #pragma warning restore CS1591
        [EnumMember(Value = "postgres")]
        #pragma warning disable CS1591
        Postgres,
        #pragma warning restore CS1591
        [EnumMember(Value = "kafka")]
        #pragma warning disable CS1591
        Kafka,
        #pragma warning restore CS1591
        [EnumMember(Value = "nats")]
        #pragma warning disable CS1591
        Nats,
        #pragma warning restore CS1591
        [EnumMember(Value = "mqtt")]
        #pragma warning disable CS1591
        Mqtt,
        #pragma warning restore CS1591
        [EnumMember(Value = "amqp")]
        #pragma warning disable CS1591
        Amqp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sqs")]
        #pragma warning disable CS1591
        Sqs,
        #pragma warning restore CS1591
        [EnumMember(Value = "gcp")]
        #pragma warning disable CS1591
        Gcp,
        #pragma warning restore CS1591
        [EnumMember(Value = "azure")]
        #pragma warning disable CS1591
        Azure,
        #pragma warning restore CS1591
        [EnumMember(Value = "google")]
        #pragma warning disable CS1591
        Google,
        #pragma warning restore CS1591
        [EnumMember(Value = "github")]
        #pragma warning disable CS1591
        Github,
        #pragma warning restore CS1591
        [EnumMember(Value = "asset")]
        #pragma warning disable CS1591
        Asset,
        #pragma warning restore CS1591
        [EnumMember(Value = "freshness")]
        #pragma warning disable CS1591
        Freshness,
        #pragma warning restore CS1591
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
        [EnumMember(Value = "ui")]
        #pragma warning disable CS1591
        Ui,
        #pragma warning restore CS1591
    }
}
