// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>
    /// Full trigger response containing both Windmill data and external service data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetNativeTrigger200Response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Error message if the trigger is in an error state</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Configuration data from the external service. Null when the service has no such API, or when it could not be read — see external_error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseExternalData? ExternalData { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseExternalData ExternalData { get; set; }
#endif
        /// <summary>Why the external service configuration could not be read. When set, external_data is null and the configuration Windmill stored is returned instead.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalError { get; set; }
#nullable restore
#else
        public string ExternalError { get; set; }
#endif
        /// <summary>The unique identifier from the external service</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Whether the trigger targets a flow (true) or a script (false)</summary>
        public bool? IsFlow { get; set; }
        /// <summary>The path to the script or flow that will be triggered</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptPath { get; set; }
#nullable restore
#else
        public string ScriptPath { get; set; }
#endif
        /// <summary>Configuration for the trigger including event_type and service_config</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceConfig? ServiceConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceConfig ServiceConfig { get; set; }
#endif
        /// <summary>The service_name property</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceName? ServiceName { get; set; }
        /// <summary>Short summary to be displayed when listed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Summary { get; set; }
#nullable restore
#else
        public string Summary { get; set; }
#endif
        /// <summary>The workspace this trigger belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceId { get; set; }
#nullable restore
#else
        public string WorkspaceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200Response"/> and sets the default values.
        /// </summary>
        public GetNativeTrigger200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetStringValue(); } },
                { "external_data", n => { ExternalData = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseExternalData>(global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseExternalData.CreateFromDiscriminatorValue); } },
                { "external_error", n => { ExternalError = n.GetStringValue(); } },
                { "external_id", n => { ExternalId = n.GetStringValue(); } },
                { "is_flow", n => { IsFlow = n.GetBoolValue(); } },
                { "script_path", n => { ScriptPath = n.GetStringValue(); } },
                { "service_config", n => { ServiceConfig = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceConfig>(global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceConfig.CreateFromDiscriminatorValue); } },
                { "service_name", n => { ServiceName = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceName>(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseExternalData>("external_data", ExternalData);
            writer.WriteStringValue("external_error", ExternalError);
            writer.WriteStringValue("external_id", ExternalId);
            writer.WriteBoolValue("is_flow", IsFlow);
            writer.WriteStringValue("script_path", ScriptPath);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceConfig>("service_config", ServiceConfig);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.GetNativeTrigger200ResponseServiceName>("service_name", ServiceName);
            writer.WriteStringValue("summary", Summary);
            writer.WriteStringValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
