// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListNatsTriggers200ResponseSchemaItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>JetStream consumer name (required when use_jetstream is true)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConsumerName { get; set; }
#nullable restore
#else
        public string ConsumerName { get; set; }
#endif
        /// <summary>True when this row is a per-user draft with no deployedtrigger at the same path. Set by list endpoints when`include_draft_only=true` synthesizes the row from thedraft. Frontend renders a &quot;Draft&quot; badge.</summary>
        public bool? DraftOnly { get; set; }
        /// <summary>Timestamp of the last edit</summary>
        public DateTimeOffset? EditedAt { get; set; }
        /// <summary>Username of the last person who edited this trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EditedBy { get; set; }
#nullable restore
#else
        public string EditedBy { get; set; }
#endif
        /// <summary>Last error message if the trigger failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The arguments to pass to the script or flow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemErrorHandlerArgs? ErrorHandlerArgs { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemErrorHandlerArgs ErrorHandlerArgs { get; set; }
#endif
        /// <summary>Path to a script or flow to run when the triggered job fails</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ErrorHandlerPath { get; set; }
#nullable restore
#else
        public string ErrorHandlerPath { get; set; }
#endif
        /// <summary>Additional permissions for this trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemExtraPerms? ExtraPerms { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemExtraPerms ExtraPerms { get; set; }
#endif
        /// <summary>True when the authed user has a per-user draft at this path(over a deployed row or a synthesized draft-only row).Frontend appends a `*` to the displayed name.</summary>
        public bool? IsDraft { get; set; }
        /// <summary>True if script_path points to a flow, false if it points to a script</summary>
        public bool? IsFlow { get; set; }
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Labels { get; set; }
#nullable restore
#else
        public List<string> Labels { get; set; }
#endif
        /// <summary>Timestamp of last server heartbeat (internal)</summary>
        public DateTimeOffset? LastServerPing { get; set; }
        /// <summary>job trigger mode</summary>
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemMode? Mode { get; set; }
        /// <summary>Path to the NATS resource containing connection configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NatsResourcePath { get; set; }
#nullable restore
#else
        public string NatsResourcePath { get; set; }
#endif
        /// <summary>The unique Windmill path for this trigger. Must be of the form `u/&lt;user&gt;/&lt;path&gt;` or `f/&lt;folder&gt;/&lt;path&gt;`. This is the trigger object path, not the HTTP route path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Path { get; set; }
#nullable restore
#else
        public string Path { get; set; }
#endif
        /// <summary>The user or group this trigger runs as (permissioned_as)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionedAs { get; set; }
#nullable restore
#else
        public string PermissionedAs { get; set; }
#endif
        /// <summary>Retry configuration for failed module executions</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemRetry? Retry { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemRetry Retry { get; set; }
#endif
        /// <summary>Path to the script or flow to execute when triggered</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScriptPath { get; set; }
#nullable restore
#else
        public string ScriptPath { get; set; }
#endif
        /// <summary>ID of the server currently handling this trigger (internal)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ServerId { get; set; }
#nullable restore
#else
        public string ServerId { get; set; }
#endif
        /// <summary>JetStream stream name (required when use_jetstream is true)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StreamName { get; set; }
#nullable restore
#else
        public string StreamName { get; set; }
#endif
        /// <summary>Array of NATS subjects to subscribe to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Subjects { get; set; }
#nullable restore
#else
        public List<string> Subjects { get; set; }
#endif
        /// <summary>If true, uses NATS JetStream for durable message delivery</summary>
        public bool? UseJetstream { get; set; }
        /// <summary>The workspace this trigger belongs to</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceId { get; set; }
#nullable restore
#else
        public string WorkspaceId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseSchemaItem"/> and sets the default values.
        /// </summary>
        public ListNatsTriggers200ResponseSchemaItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseSchemaItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseSchemaItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseSchemaItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "consumer_name", n => { ConsumerName = n.GetStringValue(); } },
                { "draft_only", n => { DraftOnly = n.GetBoolValue(); } },
                { "edited_at", n => { EditedAt = n.GetDateTimeOffsetValue(); } },
                { "edited_by", n => { EditedBy = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "error_handler_args", n => { ErrorHandlerArgs = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemErrorHandlerArgs>(global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemErrorHandlerArgs.CreateFromDiscriminatorValue); } },
                { "error_handler_path", n => { ErrorHandlerPath = n.GetStringValue(); } },
                { "extra_perms", n => { ExtraPerms = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemExtraPerms>(global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemExtraPerms.CreateFromDiscriminatorValue); } },
                { "is_draft", n => { IsDraft = n.GetBoolValue(); } },
                { "is_flow", n => { IsFlow = n.GetBoolValue(); } },
                { "labels", n => { Labels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "last_server_ping", n => { LastServerPing = n.GetDateTimeOffsetValue(); } },
                { "mode", n => { Mode = n.GetEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemMode>(); } },
                { "nats_resource_path", n => { NatsResourcePath = n.GetStringValue(); } },
                { "path", n => { Path = n.GetStringValue(); } },
                { "permissioned_as", n => { PermissionedAs = n.GetStringValue(); } },
                { "retry", n => { Retry = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemRetry>(global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemRetry.CreateFromDiscriminatorValue); } },
                { "script_path", n => { ScriptPath = n.GetStringValue(); } },
                { "server_id", n => { ServerId = n.GetStringValue(); } },
                { "stream_name", n => { StreamName = n.GetStringValue(); } },
                { "subjects", n => { Subjects = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "use_jetstream", n => { UseJetstream = n.GetBoolValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("consumer_name", ConsumerName);
            writer.WriteBoolValue("draft_only", DraftOnly);
            writer.WriteDateTimeOffsetValue("edited_at", EditedAt);
            writer.WriteStringValue("edited_by", EditedBy);
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemErrorHandlerArgs>("error_handler_args", ErrorHandlerArgs);
            writer.WriteStringValue("error_handler_path", ErrorHandlerPath);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemExtraPerms>("extra_perms", ExtraPerms);
            writer.WriteBoolValue("is_draft", IsDraft);
            writer.WriteBoolValue("is_flow", IsFlow);
            writer.WriteCollectionOfPrimitiveValues<string>("labels", Labels);
            writer.WriteDateTimeOffsetValue("last_server_ping", LastServerPing);
            writer.WriteEnumValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemMode>("mode", Mode);
            writer.WriteStringValue("nats_resource_path", NatsResourcePath);
            writer.WriteStringValue("path", Path);
            writer.WriteStringValue("permissioned_as", PermissionedAs);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.ListNatsTriggers200ResponseItemRetry>("retry", Retry);
            writer.WriteStringValue("script_path", ScriptPath);
            writer.WriteStringValue("server_id", ServerId);
            writer.WriteStringValue("stream_name", StreamName);
            writer.WriteCollectionOfPrimitiveValues<string>("subjects", Subjects);
            writer.WriteBoolValue("use_jetstream", UseJetstream);
            writer.WriteStringValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
