// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListAiSessionBackups200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>bumped by every workspace key rotation; sync state recorded under another one is void</summary>
        public int? BackupGeneration { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>the storage answered from is the instance object store, standing in for a workspace without storage of its own; a removal owed to it is retired by any answer from the workspace&apos;s own storage</summary>
        public bool? Fallback { get; set; }
        /// <summary>the newest 500 at most</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200ResponseSessionsItem>? Sessions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200ResponseSessionsItem> Sessions { get; set; }
#endif
        /// <summary>names the storage answered from; sync state recorded against another one is void</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StorageId { get; set; }
#nullable restore
#else
        public string StorageId { get; set; }
#endif
        /// <summary>the user has more sessions than the answer names</summary>
        public bool? Truncated { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200Response"/> and sets the default values.
        /// </summary>
        public ListAiSessionBackups200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup_generation", n => { BackupGeneration = n.GetIntValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "fallback", n => { Fallback = n.GetBoolValue(); } },
                { "sessions", n => { Sessions = n.GetCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200ResponseSessionsItem>(global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200ResponseSessionsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "storage_id", n => { StorageId = n.GetStringValue(); } },
                { "truncated", n => { Truncated = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("backup_generation", BackupGeneration);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("fallback", Fallback);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Windmill.OpenApiClient.Models.ListAiSessionBackups200ResponseSessionsItem>("sessions", Sessions);
            writer.WriteStringValue("storage_id", StorageId);
            writer.WriteBoolValue("truncated", Truncated);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
