// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>The kind of client the change came from. `worker` means the server disabled the trigger on its own after a failure.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListTriggerHistory200ResponseItemSource
    {
        [EnumMember(Value = "ui")]
        #pragma warning disable CS1591
        Ui,
        #pragma warning restore CS1591
        [EnumMember(Value = "cli")]
        #pragma warning disable CS1591
        Cli,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "worker")]
        #pragma warning disable CS1591
        Worker,
        #pragma warning restore CS1591
    }
}
