// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    /// <summary>Azure Event Grid trigger mode.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListAzureTriggers200ResponseItemAzureMode
    {
        [EnumMember(Value = "basic_push")]
        #pragma warning disable CS1591
        BasicPush,
        #pragma warning restore CS1591
        [EnumMember(Value = "namespace_push")]
        #pragma warning disable CS1591
        NamespacePush,
        #pragma warning restore CS1591
        [EnumMember(Value = "namespace_pull")]
        #pragma warning disable CS1591
        NamespacePull,
        #pragma warning restore CS1591
    }
}
