// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateResourceTypeRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>File extension for a type whose value is one file rather than a set of fields. Omit to leave it unchanged; send null to clear it.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormatExtension { get; set; }
#nullable restore
#else
        public string FormatExtension { get; set; }
#endif
        /// <summary>The is_fileset property</summary>
        public bool? IsFileset { get; set; }
        /// <summary>The schema property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequestSchema? Schema { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequestSchema Schema { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequest"/> and sets the default values.
        /// </summary>
        public UpdateResourceTypeRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "format_extension", n => { FormatExtension = n.GetStringValue(); } },
                { "is_fileset", n => { IsFileset = n.GetBoolValue(); } },
                { "schema", n => { Schema = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequestSchema>(global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequestSchema.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("format_extension", FormatExtension);
            writer.WriteBoolValue("is_fileset", IsFileset);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateResourceTypeRequestSchema>("schema", Schema);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
