// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateEvalDatasetRequestCasesItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Reference output a scorer compares a rerun against.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemExpected? Expected { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemExpected Expected { get; set; }
#endif
        /// <summary>Absent for a case the dataset does not hold yet.</summary>
        public Guid? Id { get; set; }
        /// <summary>The inputs a standalone run feeds the agent.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemInput? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemInput Input { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItem"/> and sets the default values.
        /// </summary>
        public UpdateEvalDatasetRequestCasesItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "expected", n => { Expected = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemExpected>(global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemExpected.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemInput>(global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemInput.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemExpected>("expected", Expected);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Windmill.OpenApiClient.Models.UpdateEvalDatasetRequestCasesItemInput>("input", Input);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
