// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Windmill.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UpdateFlow_value_preprocessor_module_valueMember4_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "forloopflow")]
        #pragma warning disable CS1591
        Forloopflow,
        #pragma warning restore CS1591
    }
}
