// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Files;
using Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Shared_drives;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\native_triggers\google\drive
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DriveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shared_drives property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Shared_drives.Shared_drivesRequestBuilder Shared_drives
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.Shared_drives.Shared_drivesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.DriveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DriveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/native_triggers/google/drive", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Google.Drive.DriveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DriveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/native_triggers/google/drive", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
