// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune
{
    /// <summary>
    /// Builds and executes requests for operations under \concurrency_groups\prune
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PruneRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.concurrency_groups.prune.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.Item.WithConcurrency_ItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.Item.WithConcurrency_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("concurrency_id", position);
                return new global::Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.Item.WithConcurrency_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.PruneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PruneRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/concurrency_groups/prune", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Concurrency_groups.Prune.PruneRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PruneRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/concurrency_groups/prune", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
