// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Apply;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Plan;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\workspaces\datatable_acl\{datatableName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDatatableNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apply property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Apply.ApplyRequestBuilder Apply
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Apply.ApplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plan property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Plan.PlanRequestBuilder Plan
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.Plan.PlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDatatableNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/datatable_acl/{datatableName}?kind={kind}{&schema*,table*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDatatableNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/datatable_acl/{datatableName}?kind={kind}{&schema*,table*}", rawUrl)
        {
        }
        /// <summary>
        /// read the owner and grants of an instance data table&apos;s database, schema or table
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAcl200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAcl200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAcl200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAcl200Response>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAcl200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// read the owner and grants of an instance data table&apos;s database, schema or table
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Datatable_acl.Item.WithDatatableNameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// read the owner and grants of an instance data table&apos;s database, schema or table
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDatatableNameItemRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("kind")]
            public global::Soenneker.Windmill.OpenApiClient.Models.GetDatatableAclKindParameter? Kind { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("schema")]
            public string? Schema { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("schema")]
            public string Schema { get; set; }
            #pragma warning restore CS1591
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("table")]
            public string? Table { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("table")]
            public string Table { get; set; }
            #pragma warning restore CS1591
#endif
        }
    }
}
#pragma warning restore CS0618
