// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\npm_proxy\resolve
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResolveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.w.item.npm_proxy.resolve.item collection</summary>
        /// <param name="position">npm package name</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.Item.WithPackageItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.Item.WithPackageItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("package", position);
                return new global::Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.Item.WithPackageItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.ResolveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResolveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/npm_proxy/resolve", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Npm_proxy.Resolve.ResolveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ResolveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/npm_proxy/resolve", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
