// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Apps.List
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\apps\list
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/apps/list{?created_by*,include_draft_only*,label*,order_desc*,page*,path_exact*,path_start*,per_page*,starred_only*,with_deployment_msg*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/apps/list{?created_by*,include_draft_only*,label*,order_desc*,page*,path_exact*,path_start*,per_page*,starred_only*,with_deployment_msg*}", rawUrl)
        {
        }
        /// <summary>
        /// list all apps
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Windmill.OpenApiClient.Models.ListApps200&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListApps200>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListApps200>> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Windmill.OpenApiClient.Models.ListApps200>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.ListApps200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// list all apps
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder.ListRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Apps.List.ListRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// list all apps
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListRequestBuilderGetQueryParameters 
        {
            /// <summary>filter by exact matching user creator. Supports comma-separated list (e.g. &apos;alice,bob&apos;) and negation by prefixing all values with &apos;!&apos; (e.g. &apos;!alice,!bob&apos;)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_by")]
            public string? CreatedBy { get; set; }
#nullable restore
#else
            [QueryParameter("created_by")]
            public string CreatedBy { get; set; }
#endif
            /// <summary>(default false)include items that have no deployed version</summary>
            [QueryParameter("include_draft_only")]
            public bool? IncludeDraftOnly { get; set; }
            /// <summary>Filter by label</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("label")]
            public string? Label { get; set; }
#nullable restore
#else
            [QueryParameter("label")]
            public string Label { get; set; }
#endif
            /// <summary>order by desc order (default true)</summary>
            [QueryParameter("order_desc")]
            public bool? OrderDesc { get; set; }
            /// <summary>which page to return (start at 1, default 1)</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>mask to filter exact matching path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("path_exact")]
            public string? PathExact { get; set; }
#nullable restore
#else
            [QueryParameter("path_exact")]
            public string PathExact { get; set; }
#endif
            /// <summary>mask to filter matching starting path</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("path_start")]
            public string? PathStart { get; set; }
#nullable restore
#else
            [QueryParameter("path_start")]
            public string PathStart { get; set; }
#endif
            /// <summary>number of items to return for a given page (default 30, max 100)</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
            /// <summary>(default false)show only the starred items</summary>
            [QueryParameter("starred_only")]
            public bool? StarredOnly { get; set; }
            /// <summary>(default false)include deployment message</summary>
            [QueryParameter("with_deployment_msg")]
            public bool? WithDeploymentMsg { get; set; }
        }
    }
}
#pragma warning restore CS0618
