// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Add_user;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Archive;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_channels;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_ids;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_color;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_id;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_name;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Cloud_quotas;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Compare;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_slack;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_teams;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_fork;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_pg_database;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_service_account;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_workspace_fork_branch;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_app;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_scripts;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_git_sync_repository;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_invite;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Drop_forked_datatable_databases;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_auto_invite;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_copilot_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_datatable_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_default_app;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_to;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_ui_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_ducklake_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_error_handler;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_repository;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_instance_groups;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_large_file_storage_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_slack_command;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_success_handler;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_teams_command;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_webhook;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Encryption_key;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Export_pg_schema;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_as_superadmin;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_info;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_settings_state;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_full_schema;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_table_schema;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependency_map;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents_amounts;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_deploy_to;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_imports;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_public_settings;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_secondary_storage_names;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_settings;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_workspace_name;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Git_sync_enabled;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Import_pg_database;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Invite_user;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Is_premium;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Leave;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_schemas;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_tables;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatables;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_ducklakes;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_pending_invites;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Log_chat;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Operator_settings;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Premium_info;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Protection_rules;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Prune_versions;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Public_app_rate_limit;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Rebuild_dependency_map;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Reset_diff_tally;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_slack_message_test_job;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_teams_message_test_job;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Set_environment_variable;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Slack_oauth_config;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Threshold_alert;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Usage;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Used_triggers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Workspaces
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\workspaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkspacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The add_user property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Add_user.Add_userRequestBuilder Add_user
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Add_user.Add_userRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The archive property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Archive.ArchiveRequestBuilder Archive
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Archive.ArchiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The available_teams_channels property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_channels.Available_teams_channelsRequestBuilder Available_teams_channels
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_channels.Available_teams_channelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The available_teams_ids property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_ids.Available_teams_idsRequestBuilder Available_teams_ids
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Available_teams_ids.Available_teams_idsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The change_workspace_color property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_color.Change_workspace_colorRequestBuilder Change_workspace_color
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_color.Change_workspace_colorRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The change_workspace_id property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_id.Change_workspace_idRequestBuilder Change_workspace_id
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_id.Change_workspace_idRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The change_workspace_name property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_name.Change_workspace_nameRequestBuilder Change_workspace_name
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Change_workspace_name.Change_workspace_nameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cloud_quotas property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Cloud_quotas.Cloud_quotasRequestBuilder Cloud_quotas
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Cloud_quotas.Cloud_quotasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The compare property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Compare.CompareRequestBuilder Compare
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Compare.CompareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connect_slack property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_slack.Connect_slackRequestBuilder Connect_slack
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_slack.Connect_slackRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The connect_teams property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_teams.Connect_teamsRequestBuilder Connect_teams
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Connect_teams.Connect_teamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create_fork property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_fork.Create_forkRequestBuilder Create_fork
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_fork.Create_forkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create_pg_database property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_pg_database.Create_pg_databaseRequestBuilder Create_pg_database
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_pg_database.Create_pg_databaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create_service_account property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_service_account.Create_service_accountRequestBuilder Create_service_account
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_service_account.Create_service_accountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The create_workspace_fork_branch property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_workspace_fork_branch.Create_workspace_fork_branchRequestBuilder Create_workspace_fork_branch
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Create_workspace_fork_branch.Create_workspace_fork_branchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The critical_alerts property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder Critical_alerts
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Critical_alerts.Critical_alertsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The default_app property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_app.Default_appRequestBuilder Default_app
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_app.Default_appRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The default_scripts property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_scripts.Default_scriptsRequestBuilder Default_scripts
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Default_scripts.Default_scriptsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_git_sync_repository property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_git_sync_repository.Delete_git_sync_repositoryRequestBuilder Delete_git_sync_repository
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_git_sync_repository.Delete_git_sync_repositoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_invite property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_invite.Delete_inviteRequestBuilder Delete_invite
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Delete_invite.Delete_inviteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The drop_forked_datatable_databases property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Drop_forked_datatable_databases.Drop_forked_datatable_databasesRequestBuilder Drop_forked_datatable_databases
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Drop_forked_datatable_databases.Drop_forked_datatable_databasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_auto_invite property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_auto_invite.Edit_auto_inviteRequestBuilder Edit_auto_invite
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_auto_invite.Edit_auto_inviteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_copilot_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_copilot_config.Edit_copilot_configRequestBuilder Edit_copilot_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_copilot_config.Edit_copilot_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_datatable_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_datatable_config.Edit_datatable_configRequestBuilder Edit_datatable_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_datatable_config.Edit_datatable_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_default_app property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_default_app.Edit_default_appRequestBuilder Edit_default_app
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_default_app.Edit_default_appRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_deploy_to property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_to.Edit_deploy_toRequestBuilder Edit_deploy_to
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_to.Edit_deploy_toRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_deploy_ui_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_ui_config.Edit_deploy_ui_configRequestBuilder Edit_deploy_ui_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_deploy_ui_config.Edit_deploy_ui_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_ducklake_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_ducklake_config.Edit_ducklake_configRequestBuilder Edit_ducklake_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_ducklake_config.Edit_ducklake_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_error_handler property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_error_handler.Edit_error_handlerRequestBuilder Edit_error_handler
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_error_handler.Edit_error_handlerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_git_sync_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_config.Edit_git_sync_configRequestBuilder Edit_git_sync_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_config.Edit_git_sync_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_git_sync_repository property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_repository.Edit_git_sync_repositoryRequestBuilder Edit_git_sync_repository
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_git_sync_repository.Edit_git_sync_repositoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_instance_groups property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_instance_groups.Edit_instance_groupsRequestBuilder Edit_instance_groups
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_instance_groups.Edit_instance_groupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_large_file_storage_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_large_file_storage_config.Edit_large_file_storage_configRequestBuilder Edit_large_file_storage_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_large_file_storage_config.Edit_large_file_storage_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_slack_command property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_slack_command.Edit_slack_commandRequestBuilder Edit_slack_command
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_slack_command.Edit_slack_commandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_success_handler property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_success_handler.Edit_success_handlerRequestBuilder Edit_success_handler
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_success_handler.Edit_success_handlerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_teams_command property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_teams_command.Edit_teams_commandRequestBuilder Edit_teams_command
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_teams_command.Edit_teams_commandRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The edit_webhook property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_webhook.Edit_webhookRequestBuilder Edit_webhook
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Edit_webhook.Edit_webhookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The encryption_key property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Encryption_key.Encryption_keyRequestBuilder Encryption_key
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Encryption_key.Encryption_keyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export_pg_schema property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Export_pg_schema.Export_pg_schemaRequestBuilder Export_pg_schema
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Export_pg_schema.Export_pg_schemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_as_superadmin property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_as_superadmin.Get_as_superadminRequestBuilder Get_as_superadmin
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_as_superadmin.Get_as_superadminRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_copilot_info property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_info.Get_copilot_infoRequestBuilder Get_copilot_info
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_info.Get_copilot_infoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_copilot_settings_state property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_settings_state.Get_copilot_settings_stateRequestBuilder Get_copilot_settings_state
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_copilot_settings_state.Get_copilot_settings_stateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_datatable_full_schema property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_full_schema.Get_datatable_full_schemaRequestBuilder Get_datatable_full_schema
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_full_schema.Get_datatable_full_schemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_datatable_table_schema property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_table_schema.Get_datatable_table_schemaRequestBuilder Get_datatable_table_schema
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_datatable_table_schema.Get_datatable_table_schemaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_dependency_map property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependency_map.Get_dependency_mapRequestBuilder Get_dependency_map
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependency_map.Get_dependency_mapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_dependents property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents.Get_dependentsRequestBuilder Get_dependents
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents.Get_dependentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_dependents_amounts property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents_amounts.Get_dependents_amountsRequestBuilder Get_dependents_amounts
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_dependents_amounts.Get_dependents_amountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_deploy_to property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_deploy_to.Get_deploy_toRequestBuilder Get_deploy_to
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_deploy_to.Get_deploy_toRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_imports property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_imports.Get_importsRequestBuilder Get_imports
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_imports.Get_importsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_public_settings property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_public_settings.Get_public_settingsRequestBuilder Get_public_settings
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_public_settings.Get_public_settingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_secondary_storage_names property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_secondary_storage_names.Get_secondary_storage_namesRequestBuilder Get_secondary_storage_names
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_secondary_storage_names.Get_secondary_storage_namesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_settings property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_settings.Get_settingsRequestBuilder Get_settings
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_settings.Get_settingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_workspace_name property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_workspace_name.Get_workspace_nameRequestBuilder Get_workspace_name
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Get_workspace_name.Get_workspace_nameRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The git_sync_enabled property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Git_sync_enabled.Git_sync_enabledRequestBuilder Git_sync_enabled
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Git_sync_enabled.Git_sync_enabledRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The import_pg_database property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Import_pg_database.Import_pg_databaseRequestBuilder Import_pg_database
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Import_pg_database.Import_pg_databaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invite_user property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Invite_user.Invite_userRequestBuilder Invite_user
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Invite_user.Invite_userRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The is_premium property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Is_premium.Is_premiumRequestBuilder Is_premium
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Is_premium.Is_premiumRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leave property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Leave.LeaveRequestBuilder Leave
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Leave.LeaveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_datatable_schemas property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_schemas.List_datatable_schemasRequestBuilder List_datatable_schemas
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_schemas.List_datatable_schemasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_datatable_tables property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_tables.List_datatable_tablesRequestBuilder List_datatable_tables
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatable_tables.List_datatable_tablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_datatables property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatables.List_datatablesRequestBuilder List_datatables
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_datatables.List_datatablesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_ducklakes property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_ducklakes.List_ducklakesRequestBuilder List_ducklakes
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_ducklakes.List_ducklakesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_pending_invites property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_pending_invites.List_pending_invitesRequestBuilder List_pending_invites
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.List_pending_invites.List_pending_invitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The log_chat property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Log_chat.Log_chatRequestBuilder Log_chat
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Log_chat.Log_chatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The operator_settings property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Operator_settings.Operator_settingsRequestBuilder Operator_settings
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Operator_settings.Operator_settingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The premium_info property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Premium_info.Premium_infoRequestBuilder Premium_info
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Premium_info.Premium_infoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The protection_rules property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Protection_rules.Protection_rulesRequestBuilder Protection_rules
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Protection_rules.Protection_rulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The prune_versions property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Prune_versions.Prune_versionsRequestBuilder Prune_versions
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Prune_versions.Prune_versionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The public_app_rate_limit property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Public_app_rate_limit.Public_app_rate_limitRequestBuilder Public_app_rate_limit
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Public_app_rate_limit.Public_app_rate_limitRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rebuild_dependency_map property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Rebuild_dependency_map.Rebuild_dependency_mapRequestBuilder Rebuild_dependency_map
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Rebuild_dependency_map.Rebuild_dependency_mapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reset_diff_tally property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Reset_diff_tally.Reset_diff_tallyRequestBuilder Reset_diff_tally
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Reset_diff_tally.Reset_diff_tallyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run_slack_message_test_job property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_slack_message_test_job.Run_slack_message_test_jobRequestBuilder Run_slack_message_test_job
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_slack_message_test_job.Run_slack_message_test_jobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The run_teams_message_test_job property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_teams_message_test_job.Run_teams_message_test_jobRequestBuilder Run_teams_message_test_job
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_teams_message_test_job.Run_teams_message_test_jobRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The set_environment_variable property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Set_environment_variable.Set_environment_variableRequestBuilder Set_environment_variable
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Set_environment_variable.Set_environment_variableRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The slack_oauth_config property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Slack_oauth_config.Slack_oauth_configRequestBuilder Slack_oauth_config
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Slack_oauth_config.Slack_oauth_configRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The threshold_alert property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Threshold_alert.Threshold_alertRequestBuilder Threshold_alert
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Threshold_alert.Threshold_alertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The usage property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Usage.UsageRequestBuilder Usage
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Usage.UsageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The used_triggers property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Used_triggers.Used_triggersRequestBuilder Used_triggers
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Used_triggers.Used_triggersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.WorkspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.WorkspacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkspacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
