// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\workspaces\run_datatable_migrations\{datatableName}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDatatableNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDatatableNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/run_datatable_migrations/{datatableName}{?only*,up_to*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDatatableNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/run_datatable_migrations/{datatableName}{?only*,up_to*}", rawUrl)
        {
        }
        /// <summary>
        /// run pending datatable migrations against a datatable
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Models.RunDatatableMigrations200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.RunDatatableMigrations200Response?> PostAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Windmill.OpenApiClient.Models.RunDatatableMigrations200Response> PostAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Windmill.OpenApiClient.Models.RunDatatableMigrations200Response>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.RunDatatableMigrations200Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// run pending datatable migrations against a datatable
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder.WithDatatableNameItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Run_datatable_migrations.Item.WithDatatableNameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// run pending datatable migrations against a datatable
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithDatatableNameItemRequestBuilderPostQueryParameters 
        {
            /// <summary>apply only this specific migration version, ignoring others</summary>
            [QueryParameter("only")]
            public long? Only { get; set; }
            /// <summary>only apply pending migrations up to and including this version</summary>
            [QueryParameter("up_to")]
            public long? UpTo { get; set; }
        }
    }
}
#pragma warning restore CS0618
