// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Cancel;
using Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Close_merged;
using Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Comment;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\deployment_request\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Deployment_requestItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cancel property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Cancel.CancelRequestBuilder Cancel
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Cancel.CancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The close_merged property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Close_merged.Close_mergedRequestBuilder Close_merged
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Close_merged.Close_mergedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The comment property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Comment.CommentRequestBuilder Comment
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Comment.CommentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Deployment_requestItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Deployment_requestItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/deployment_request/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Deployment_request.Item.Deployment_requestItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Deployment_requestItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/deployment_request/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
