// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \scripts_u\tokened_raw\{workspace}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithWorkspaceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.scripts_u.tokened_raw.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.Item.WithTokenItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.Item.WithTokenItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("token", position);
                return new global::Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.Item.WithTokenItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.WithWorkspaceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkspaceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scripts_u/tokened_raw/{workspace}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Scripts_u.Tokened_raw.Item.WithWorkspaceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithWorkspaceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/scripts_u/tokened_raw/{workspace}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
