// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\native_triggers\{service_name}\delete
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeleteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.w.item.native_triggers.item.delete.item collection</summary>
        /// <param name="position">The external ID of the trigger from the external service</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.Item.WithExternal_ItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.Item.WithExternal_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("external_id", position);
                return new global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.Item.WithExternal_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/native_triggers/{service_name}/delete", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Native_triggers.Item.Delete.DeleteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeleteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/native_triggers/{service_name}/delete", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
