// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\schedules\list_with_jobs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class List_with_jobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public List_with_jobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/schedules/list_with_jobs{?page*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public List_with_jobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/schedules/list_with_jobs{?page*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// list schedules with last 20 jobs
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Windmill.OpenApiClient.Models.ListSchedulesWithJobs_200&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListSchedulesWithJobs_200>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder.List_with_jobsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListSchedulesWithJobs_200>> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder.List_with_jobsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Windmill.OpenApiClient.Models.ListSchedulesWithJobs_200>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.ListSchedulesWithJobs_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// list schedules with last 20 jobs
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder.List_with_jobsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder.List_with_jobsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Schedules.List_with_jobs.List_with_jobsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// list schedules with last 20 jobs
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class List_with_jobsRequestBuilderGetQueryParameters 
        {
            /// <summary>which page to return (start at 1, default 1)</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>number of items to return for a given page (default 30, max 100)</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
    }
}
#pragma warning restore CS0618
