// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\github_app\export
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExportRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.w.item.github_app.export.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.Item.WithInstallationItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.Item.WithInstallationItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("installationId", position);
                return new global::Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.Item.WithInstallationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/github_app/export", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Github_app.Export.ExportRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ExportRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/github_app/export", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
