// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Runnables.Counts;
using Soenneker.Windmill.OpenApiClient.W.Item.Runnables.List;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Runnables
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\runnables
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RunnablesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The counts property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.Counts.CountsRequestBuilder Counts
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.Counts.CountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.RunnablesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunnablesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/runnables", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Runnables.RunnablesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RunnablesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/runnables", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
