// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\workspaces\seed_full_diff
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Seed_full_diffRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Windmill.OpenApiClient.w.item.workspaces.seed_full_diff.item collection</summary>
        /// <param name="position">The ID of the workspace to compare with</param>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Item.WithTargetWorkspaceItemRequestBuilder"/></returns>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Item.WithTargetWorkspaceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("targetWorkspaceId", position);
                return new global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Item.WithTargetWorkspaceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Seed_full_diffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Seed_full_diffRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/seed_full_diff", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Workspaces.Seed_full_diff.Seed_full_diffRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Seed_full_diffRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/workspaces/seed_full_diff", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
