// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Create;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete_bulk;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Encrypt;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Exists;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get_value;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.List;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.List_contextual;
using Soenneker.Windmill.OpenApiClient.W.Item.Variables.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Variables
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\variables
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VariablesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_bulk property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete_bulk.Delete_bulkRequestBuilder Delete_bulk
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete_bulk.Delete_bulkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The encrypt property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Encrypt.EncryptRequestBuilder Encrypt
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Encrypt.EncryptRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exists property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Exists.ExistsRequestBuilder Exists
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Exists.ExistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The get_value property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get_value.Get_valueRequestBuilder Get_value
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get_value.Get_valueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_contextual property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.List_contextual.List_contextualRequestBuilder List_contextual
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.List_contextual.List_contextualRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Update.UpdateRequestBuilder Update
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.VariablesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VariablesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/variables", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Variables.VariablesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VariablesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/variables", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
