// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens
{
    /// <summary>
    /// Builds and executes requests for operations under \agent_workers\list_blacklisted_tokens
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class List_blacklisted_tokensRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public List_blacklisted_tokensRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/agent_workers/list_blacklisted_tokens{?include_expired*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public List_blacklisted_tokensRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/agent_workers/list_blacklisted_tokens{?include_expired*}", rawUrl)
        {
        }
        /// <summary>
        /// list blacklisted agent tokens (requires super admin)
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Windmill.OpenApiClient.Models.ListBlacklistedAgentTokens200&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListBlacklistedAgentTokens200>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder.List_blacklisted_tokensRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Windmill.OpenApiClient.Models.ListBlacklistedAgentTokens200>> GetAsync(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder.List_blacklisted_tokensRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Windmill.OpenApiClient.Models.ListBlacklistedAgentTokens200>(requestInfo, global::Soenneker.Windmill.OpenApiClient.Models.ListBlacklistedAgentTokens200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// list blacklisted agent tokens (requires super admin)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder.List_blacklisted_tokensRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder.List_blacklisted_tokensRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.Agent_workers.List_blacklisted_tokens.List_blacklisted_tokensRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// list blacklisted agent tokens (requires super admin)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class List_blacklisted_tokensRequestBuilderGetQueryParameters 
        {
            /// <summary>Whether to include expired blacklisted tokens</summary>
            [QueryParameter("include_expired")]
            public bool? IncludeExpired { get; set; }
        }
    }
}
#pragma warning restore CS0618
