// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\jobs\run\f\{path}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithPathItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/jobs/run/f/{path}{?include_header*,invisible_to_owner*,job_id*,memory_id*,parent_job*,scheduled_for*,scheduled_in_secs*,skip_preprocessor*,tag*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithPathItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/jobs/run/f/{path}{?include_header*,invisible_to_owner*,job_id*,memory_id*,parent_job*,scheduled_for*,scheduled_in_secs*,skip_preprocessor*,tag*}", rawUrl)
        {
        }
        /// <summary>
        /// run flow by path
        /// </summary>
        /// <returns>A <see cref="Guid"/></returns>
        /// <param name="body">The arguments to pass to the script or flow</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Guid?> PostAsync(global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Guid?> PostAsync(global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendPrimitiveAsync<Guid?>(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// run flow by path
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The arguments to pass to the script or flow</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathPostRequestBody body, Action<RequestConfiguration<global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder.WithPathItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "text/plain;q=0.9");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Windmill.OpenApiClient.W.Item.Jobs.Run.F.Item.WithPathItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// run flow by path
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithPathItemRequestBuilderPostQueryParameters 
        {
            /// <summary>List of headers&apos;s keys (separated with &apos;,&apos;) whove value are added to the argsHeader&apos;s key lowercased and &apos;-&apos;&apos; replaced to &apos;_&apos; such that &apos;Content-Type&apos; becomes the &apos;content_type&apos; arg key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("include_header")]
            public string? IncludeHeader { get; set; }
#nullable restore
#else
            [QueryParameter("include_header")]
            public string IncludeHeader { get; set; }
#endif
            /// <summary>make the run invisible to the the flow owner (default false)</summary>
            [QueryParameter("invisible_to_owner")]
            public bool? InvisibleToOwner { get; set; }
            /// <summary>The job id to assign to the created job. if missing, job is chosen randomly using the ULID scheme. If a job id already exists in the queue or as a completed job, the request to create one will fail (Bad Request)</summary>
            [QueryParameter("job_id")]
            public Guid? JobId { get; set; }
            /// <summary>memory ID for chat-enabled flows</summary>
            [QueryParameter("memory_id")]
            public Guid? MemoryId { get; set; }
            /// <summary>The parent job that is at the origin and responsible for the execution of this script if any</summary>
            [QueryParameter("parent_job")]
            public Guid? ParentJob { get; set; }
            /// <summary>when to schedule this job (leave empty for immediate run)</summary>
            [QueryParameter("scheduled_for")]
            public DateTimeOffset? ScheduledFor { get; set; }
            /// <summary>schedule the script to execute in the number of seconds starting now</summary>
            [QueryParameter("scheduled_in_secs")]
            public int? ScheduledInSecs { get; set; }
            /// <summary>skip the preprocessor</summary>
            [QueryParameter("skip_preprocessor")]
            public bool? SkipPreprocessor { get; set; }
            /// <summary>Override the tag to use</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag")]
            public string? Tag { get; set; }
#nullable restore
#else
            [QueryParameter("tag")]
            public string Tag { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
