// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Asset_schemas;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Graph;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.List;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_by_usages;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_favorites;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Macros;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions_in_range;
using Soenneker.Windmill.OpenApiClient.W.Item.Assets.Pipelines;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Assets
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\assets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The asset_schemas property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Asset_schemas.Asset_schemasRequestBuilder Asset_schemas
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Asset_schemas.Asset_schemasRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The graph property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Graph.GraphRequestBuilder Graph
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Graph.GraphRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_by_usages property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_by_usages.List_by_usagesRequestBuilder List_by_usages
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_by_usages.List_by_usagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_favorites property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_favorites.List_favoritesRequestBuilder List_favorites
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.List_favorites.List_favoritesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The macros property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Macros.MacrosRequestBuilder Macros
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Macros.MacrosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partitions property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions.PartitionsRequestBuilder Partitions
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions.PartitionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partitions_in_range property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions_in_range.Partitions_in_rangeRequestBuilder Partitions_in_range
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Partitions_in_range.Partitions_in_rangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pipelines property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Pipelines.PipelinesRequestBuilder Pipelines
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.Pipelines.PipelinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/assets", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Assets.AssetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AssetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/assets", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
