// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Create;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Delete;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Exists;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Get;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.List;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Local_part_exists;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Setmode;
using Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Update;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\email_triggers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Email_triggersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The create property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Create.CreateRequestBuilder Create
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Create.CreateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exists property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Exists.ExistsRequestBuilder Exists
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Exists.ExistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The getPath property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Get.GetRequestBuilder GetPath
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Get.GetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.List.ListRequestBuilder List
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The local_part_exists property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Local_part_exists.Local_part_existsRequestBuilder Local_part_exists
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Local_part_exists.Local_part_existsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setmode property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Setmode.SetmodeRequestBuilder Setmode
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Setmode.SetmodeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Update.UpdateRequestBuilder Update
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Email_triggersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_triggersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/email_triggers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Email_triggers.Email_triggersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_triggersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/email_triggers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
