// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Check_s3_folder_exists;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Delete_s3_file;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_file;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_parquet_file_as_csv;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Duckdb_connection_settings;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_git_repo_files;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_stored_files;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_csv_preview;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_metadata;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_preview;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_metadata;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_preview;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_parquet_preview;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_table_count;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Move_s3_file;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Polars_connection_settings;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Test_connection;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_git_repo_file_to_instance_storage;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_s3_file;
using Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.V2;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers
{
    /// <summary>
    /// Builds and executes requests for operations under \w\{workspace}\job_helpers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Job_helpersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The check_s3_folder_exists property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Check_s3_folder_exists.Check_s3_folder_existsRequestBuilder Check_s3_folder_exists
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Check_s3_folder_exists.Check_s3_folder_existsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The delete_s3_file property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Delete_s3_file.Delete_s3_fileRequestBuilder Delete_s3_file
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Delete_s3_file.Delete_s3_fileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download_s3_file property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_file.Download_s3_fileRequestBuilder Download_s3_file
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_file.Download_s3_fileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The download_s3_parquet_file_as_csv property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_parquet_file_as_csv.Download_s3_parquet_file_as_csvRequestBuilder Download_s3_parquet_file_as_csv
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Download_s3_parquet_file_as_csv.Download_s3_parquet_file_as_csvRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The duckdb_connection_settings property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Duckdb_connection_settings.Duckdb_connection_settingsRequestBuilder Duckdb_connection_settings
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Duckdb_connection_settings.Duckdb_connection_settingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_git_repo_files property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_git_repo_files.List_git_repo_filesRequestBuilder List_git_repo_files
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_git_repo_files.List_git_repo_filesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_stored_files property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_stored_files.List_stored_filesRequestBuilder List_stored_files
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.List_stored_files.List_stored_filesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_csv_preview property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_csv_preview.Load_csv_previewRequestBuilder Load_csv_preview
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_csv_preview.Load_csv_previewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_file_metadata property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_metadata.Load_file_metadataRequestBuilder Load_file_metadata
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_metadata.Load_file_metadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_file_preview property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_preview.Load_file_previewRequestBuilder Load_file_preview
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_file_preview.Load_file_previewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_git_repo_file_metadata property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_metadata.Load_git_repo_file_metadataRequestBuilder Load_git_repo_file_metadata
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_metadata.Load_git_repo_file_metadataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_git_repo_file_preview property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_preview.Load_git_repo_file_previewRequestBuilder Load_git_repo_file_preview
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_git_repo_file_preview.Load_git_repo_file_previewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_parquet_preview property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_parquet_preview.Load_parquet_previewRequestBuilder Load_parquet_preview
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_parquet_preview.Load_parquet_previewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load_table_count property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_table_count.Load_table_countRequestBuilder Load_table_count
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Load_table_count.Load_table_countRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The move_s3_file property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Move_s3_file.Move_s3_fileRequestBuilder Move_s3_file
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Move_s3_file.Move_s3_fileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The polars_connection_settings property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Polars_connection_settings.Polars_connection_settingsRequestBuilder Polars_connection_settings
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Polars_connection_settings.Polars_connection_settingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The test_connection property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Test_connection.Test_connectionRequestBuilder Test_connection
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Test_connection.Test_connectionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_git_repo_file_to_instance_storage property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_git_repo_file_to_instance_storage.Upload_git_repo_file_to_instance_storageRequestBuilder Upload_git_repo_file_to_instance_storage
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_git_repo_file_to_instance_storage.Upload_git_repo_file_to_instance_storageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The upload_s3_file property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_s3_file.Upload_s3_fileRequestBuilder Upload_s3_file
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Upload_s3_file.Upload_s3_fileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.V2.V2RequestBuilder V2
        {
            get => new global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Job_helpersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Job_helpersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/job_helpers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Windmill.OpenApiClient.W.Item.Job_helpers.Job_helpersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Job_helpersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/w/{workspace}/job_helpers", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
